# Generated by Django 4.2 on 2023-05-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipocardapio_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Cardapio', 'verbose_name_plural': 'Cardapio'},
        ),
        migrations.AlterModelOptions(
            name='tipocardapio',
            options={'verbose_name': 'Tipo Cardapio', 'verbose_name_plural': 'Tipos Cardapio'},
        ),
        migrations.RenameField(
            model_name='tipocardapio',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
